name: alura_store

services:
  postgres:
    image: postgres:18
    container_name: alura_store_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: alura_store
    ports:
      - "5432:5432"
    volumes:
      - ./create.sql:/docker-entrypoint-initdb.d/init.sql
